### ISSUE TITLE
Reset input 

### ISSUE THREAD

**Issue by wkjesus** [adonespitogo/angular-base64-upload#13]
Hi.. how is the way to reset the input file after upload ? or reset form ???

**Comment by adonespitogo** [comment]
Hi, sorry I haven't tried it yet. Perhaps you can create your own directive and attach it to the same input field. Then just listen to a broadcast event in rootscope to reset the input field. I don't know if it's the right approach though, just my idea.

**Comment by wkjesus** [comment]
thx. dude.. ill try it, if i have success, i ll share de the directive.. greetings. !

**Comment by dsnoeck** [comment]
Any solution for this question. I cannot find a way to clear the input after submission.

**Comment by adonespitogo** [comment]
@dsnoeck I was about to look into this. Thanks for posting your solution!

**Comment by Hyzual** [comment]
I'm using this directive along with `ngModel` and I've run into the same problem. It would be nice if there was a better way to reset the file, I shouldn't have to deal with the DOM in my controller and querySelector does exaclty that.
Right now, since I use this directive in a `ngRepeat`, when I reset all my input files the solution I use is to empty the array on which the ` ngRepeat` is based and to just add the same number of inputs I had.

Is it possible to refresh the file input when I clear its model (the var bound to `ngModel`) ?

**Comment by adonespitogo** [comment]
@Hyzual this is about to be fixed in PR #64 , just waiting for Travis to finish

**Comment by adonespitogo** [comment]
To reset the input element, just assign `null`, `{}` or `[]` in your model

**Comment by adonespitogo** [comment]
e.g `$scope.file = null;`

**Comment by Hyzual** [comment]
Wow thanks for the quick reply and fix. Indeed, setting the file to `{}` does reset the view now in 0.1.17. Thanks !
I think we can close this issue again.

**Comment by adonespitogo** [comment]
Perfect!
